language: python

python:
- '2.7'

script:
- nosetests
- python -c "print('\n $pypi_username \n $pypi_secure_password \n')"

deploy:
  provider: pypi
  user: $pypi_username
  password: 
    secure: $pypi_secure_password
  distributions: sdist bdist_wheel
  on:
    tags: true
