language: python
python:
- '2.7'
- '3.2'
- '3.3'
script:
- nosetests
deploy:
  provider: pypi
  user: kressi
  password:
    secure: Rw31x5q4kz2Byld5JuboAxEISR4OIrJdobKU1mmJI8CQL8IuZOuv0w8Y7DxljQLzvCigtPFfqXkdARCXiKeYwKUAQaTVRVRf5DpPQsYlnSS8/0b6vr7XEiICkIjQN0CtB/oyXjLA7nZebgeRj45iVf4nDSzyQnjiIXpfIUTqLnA=
  distributions: sdist bdist_wheel
  on:
    tags: true
