language: python
python:
- '2.7'
- '3.2'
- '3.3'
script:
- nosetests
deploy:
  provider: pypi
  user: kressi
  password:
    secure: $pypi_secure_password
  distributions: sdist bdist_wheel
  on:
    tags: true
